server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_database
    username: parkuser
    password: parking24h
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
      ddl-auto: update
  flyway:
    url: jdbc:postgresql://localhost:5432/parking_database
    user: parkuser
    password: parking24h
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
    #placeholderReplacement: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


#management:
#  endpoint:
#    beans:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: beans

app:
  swagger-urls:
    - "http://localhost:8082"
  jwt:
    secret: bkhLWKTkNTsylUHzTkRh3DJnNEZDHgGcdCZoAxJCAkCr9Nep73NzSFJeI4NJVC1RFLbn9aozVmIXXx7V81EvvaXx9JjLLmqXCrlmyUOrS8swOCbjQywtGYaBY04JyeCo4Qj2OxKUyiX0tqUp/W202B8TKN6mnPLZRskLxtZJts6vA61WVIz1H21PzZiWHxaCChCFnbI1ICFTiPruUeRsg7g2QYArWbbubmpxtPRbe+epU8W2ZfNmvuGxmGa+YE/fdwEM7XGlBU8claNMeiYvw4/2gvMz49IN3ohcfycKOxsHtTJU13ekndBXezE7C58ODLuPJlCWI2LG/mXXiB9t
    access-expiration-ms: 90000000
    refresh-expiration-ms: 720000000