server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_database
    username: parkuser
    password: parking24h
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    enabled: true
    #placeholderReplacement: false

app:
  swagger-urls:
    - "http://localhost:8082"