version: '3.8'

services:
  db:
    image: postgres
    container_name: parking_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: parkuser
      POSTGRES_PASSWORD: parking24h
      POSTGRES_DB: parking_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



# Verzija gde su mi docker-compose.yml i kafka-compose.yml spojeni u jedan fajl
#version: '3.8'
#
#services:
#  db:
#    image: postgres
#    container_name: parking_db
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: parkuser
#      POSTGRES_PASSWORD: parking24h
#      POSTGRES_DB: parking_database
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - kafka-net
#
#  broker:
#    image: apache/kafka:latest
#    container_name: broker
#    hostname: broker
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_NUM_PARTITIONS: 3
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#    ports:
#      - "9092:9092"
#      - "9093:9093"
#    networks:
#      - kafka-net
#
#volumes:
#  postgres_data:
#
#networks:
#  kafka-net:
#    driver: bridge
