CREATE TABLE IF NOT EXISTS "parking_spot_sale" (
    id INTEGER PRIMARY KEY,
    city_id INTEGER NOT NULL,
    address VARCHAR(512) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    owner_id INTEGER NOT NULL,
    features_id INTEGER,
    "timestamp" TIMESTAMP NOT NULL,
    CONSTRAINT OWNER_FK FOREIGN KEY (owner_id) REFERENCES "user" (ID) ON DELETE CASCADE,
    CONSTRAINT CITY_FK FOREIGN KEY (city_id) REFERENCES "city" (ID) ON DELETE CASCADE,
    CONSTRAINT FEATURES_FK FOREIGN KEY (features_id) REFERENCES "features" (ID) ON DELETE CASCADE
);